=== luiscvnha/DAW2020/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (meta, team, abstract, deliverables) >

<!ELEMENT meta (key, title, subtitle?, bdate, edate, supervisor) >
<!ELEMENT key (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT bdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
    url CDATA #IMPLIED >
    
<!ELEMENT team (member+) >
<!ELEMENT member (name, email, link?) >
<!ATTLIST member
    id ID #REQUIRED >
<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (p+) >
<!ELEMENT p (#PCDATA|b|i|u|link)* >
<!ELEMENT b (#PCDATA|i|u|link)* >
<!ELEMENT i (#PCDATA|b|u|link)* >
<!ELEMENT u (#PCDATA|b|i|link)* >
<!ELEMENT link (#PCDATA) >
<!ATTLIST link
    url CDATA #REQUIRED >

<!ELEMENT deliverables (link+) >

=== luiscvnha/DAW2020/T5/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr.dtd">
<pr>
    <meta>
        <key>DAW2020_T5</key>
        <title>T5: Node.js, json-server e geração dinâmica de páginas</title>
        <bdate>novembro 2020</bdate>
        <edate>novembro 2020</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <link url="https://github.com/luiscvnha">GitHub</link>
        </member>
    </team>
    <abstract>
        <p>Atráves do json-server, é gerado automaticamente um servidor que
            disponibiliza uma API REST para uma base de dados relativa
            a uma escola de música.</p>
        <p>Foi criado um servidor Node.js com o índice dos alunos, cursos e
            instrumentos, com as respetivas páginas individuais. As páginas são
            geradas dinamicamente, sendo os dados obtidos a partir do
            json-server.</p>
        <p>Este servidor conta também com <u>tratamento de erros</u> e <u>paginação</u>.</p>
    </abstract>
    <deliverables>
        <link url="server.js">Servidor Node.js</link>
        <link url="_aux.js">Funções auxiliares</link>
    </deliverables>
</pr>

=== luiscvnha/DAW2020/T8/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr.dtd">
<pr>
    <meta>
        <key>DAW2020_T8</key>
        <title>T8: Formulários dinâmicos e upload de vários ficheiros</title>
        <bdate>dezembro 2020</bdate>
        <edate>dezembro 2020</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <link url="https://github.com/luiscvnha">GitHub</link>
        </member>
    </team>
    <abstract>
        <p>
            Neste trabalho foi implementado um formulário dinâmico que permite fazer o <i>upload</i>
            de mais que um ficheiro. Para tal, foi adicionado <b>Javascript</b> do lado do cliente
            que permite a expansão do formulário.
        </p>
        <p>
            Do lado do servidor, a função que trata o <i>upload</i> de ficheiros foi alterada de forma
            a responder tanto ao upload de um só ficheiro, como de vários.
        </p>
    </abstract>
    <deliverables>
        <link url="server.js">Servidor</link>
        <link url="html-templates.js">Templates HTML para as páginas</link>
        <link url="dbFiles.json">Base de dados de imagens</link>
        <link url="public/form.js">Javascript para o formulário dinâmico</link>
        <link url="public/imagens.js">Javascript para visualização e download das imagens</link>
        <link url="public/jquery-3.5.1.min.js">Biblioteca JQuery</link>
    </deliverables>
</pr>

=== luiscvnha/DAW2020/T4/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr.dtd">
<pr>
    <meta>
        <key>DAW2020_T4</key>
        <title>T4: XSL e servidor Node.js para o arquivo de Arqueossítios do Noroeste Português</title>
        <bdate>novembro 2020</bdate>
        <edate>novembro 2020</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <link url="https://github.com/luiscvnha">GitHub</link>
        </member>
    </team>
    <abstract>
        <p>Foi criada uma stylesheet em XSL que gera uma página html que contém o índice
            das entradas do arquivo e gera uma página para cada uma das entradas. A navegação
            entre o índice e as entradas individuais é feita a partir de um url do
            tipo <u>http://localhost:xxxx</u> ou <u>http://localhost:xxxx/arqs/y</u>, em
            que xxxx representa a <i>port</i> e y o id do arquivo.</p>
        <p>De seguida, foi criado um servidor em Node.js que atende a pedidos destes dois
            tipos. Este servidor utiliza expressões regulares para o <i>pattern matching</i>
            do url e envia códigos de erro (404) e mensagens de erro para o caso do id do
            arquivo não existir ou se o url não corresponder a nenhum dos casos válidos.
            Este servidor mantém também um log de pedidos recebidos na consola do administrador.</p>
    </abstract>
    <deliverables>
        <link url="arqsite.xsl">XSL</link>
        <link url="server.js">Servidor Node.js</link>
    </deliverables>
</pr>

=== luiscvnha/DAW2020/T7/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr.dtd">
<pr>
    <meta>
        <key>DAW2020_T7</key>
        <title>T7: Single-Page Application para Gestão de Alunos</title>
        <bdate>novembro 2020</bdate>
        <edate>novembro 2020</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <link url="https://github.com/luiscvnha">GitHub</link>
        </member>
    </team>
    <abstract>
        <p>
            Neste trabalho a persistência dos dados passou a ser garantida por uma base de dados <b>Mongo</b>
            e a sua construção passou a ser auxiliada pela <i>framework</i> <b>Express.js</b>.
        </p>
        <p>
            Foi desenvolvida uma <i>Single-Page Application</i> usando <b>AJAX</b> para a gestão de alunos, que permite
            registar um aluno, visualizar a lista de alunos, editar as suas informações e eliminá-los.
        </p>
    </abstract>
    <deliverables>
        <link url="dawApp/bin/www">Ficheiro de arranque</link>
        <link url="dawApp/app.js">Inicialização da aplicação</link>
        <link url="dawApp/controllers/student.js">Definição do controller de acesso aos dados</link>
        <link url="dawApp/models/student.js">Definição do model de aluno</link>
        <link url="dawApp/routes/index.js">Definição das rotas http</link>
        <link url="dawApp/views/index.pug">Layout da aplicação</link>
        <link url="dawApp/views/error.pug">Layout da página de erro</link>
        <link url="dawApp/common/util.js">Definição de funções auxiliares</link>
        <link url="dawApp/public/javascripts/client.js">Funções do lado do cliente</link>
        <link url="dawApp/public/stylesheets/w3.css">Framework W3.CSS</link>
        <link url="dawApp/public/stylesheets/style.css">Stylesheet adicional</link>
        <link url="dawApp/public/images/favicon.png">favicon da página</link>
        <link url="dawApp/public/images/ok.png">Icon de tpc realizado</link>
        <link url="dawApp/public/images/not.png">Icon de falta de tpc</link>
    </deliverables>
</pr>

=== luiscvnha/DAW2020/T6/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr.dtd">
<pr>
    <meta>
        <key>DAW2020_T6</key>
        <title>T6: ToDo List SPA</title>
        <bdate>novembro 2020</bdate>
        <edate>novembro 2020</edate>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <link url="https://github.com/luiscvnha">GitHub</link>
        </member>
    </team>
    <abstract>
        <p>Este trabalho consiste numa SPA (<i>Single Page Application</i>) para listas de tarefas.
            Nesta aplicação é possível adicionar, editar e remover tarefas.</p>
        <p>A página inicial é gerada dinamicamente com as tarefas atuais que são obtidas
            a partir de um servidor de base de dados (json-server), onde a informação é mantida.</p>
        <p>Esta aplicação conta com AJAX para toda a lógica da parte do cliente, é aqui que
            a aplicação comunica com o servidor e modifica a página web, sem haver reloads
            da página. Conta também com a framework W3 de CSS para tornar a interface
            mais agradável.</p>
    </abstract>
    <deliverables>
        <link url="server.js">Servidor</link>
        <link url="util.js">Funções auxiliares</link>
        <link url="static.js">Funções dedicadas a recursos estáticos</link>
        <link url="public/client.js">Javascript do lado do cliente</link>
        <link url="public/favicon.png">Icon</link>
        <link url="public/w3.css">W3 CSS</link>
    </deliverables>
</pr>
