=== luiscvnha/DAW2020/T2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (meta, workteam, abstract, deliverables) >

<!ELEMENT meta (keyname, title, subtitle?, begindate, enddate, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begindate (#PCDATA) >
<!ELEMENT enddate (#PCDATA) >
<!ELEMENT supervisor (name, url) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT url (#PCDATA) >

<!ELEMENT workteam (member, member?, member?) >
<!ELEMENT member (name, email, url?) >
<!ATTLIST member
    id ID #REQUIRED >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (p)+ >
<!ELEMENT p (#PCDATA|b|i|u|a)* >
<!ELEMENT b (#PCDATA|i|u|a)* >
<!ELEMENT i (#PCDATA|b|u|a)* >
<!ELEMENT u (#PCDATA|b|i|a)* >
<!ELEMENT a (#PCDATA|b|i|u)* >
<!ATTLIST a
    href CDATA #REQUIRED >

<!ELEMENT deliverables (deliverable)+ >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
    url CDATA #REQUIRED >

=== luiscvnha/DAW2020/T3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../T2/pr.dtd">
<pr>
    <meta>
        <keyname>DAW2020_T3</keyname>
        <title>T3: DTD e Stylesheet XSL para o arquivo de Arqueossítios do Noroeste Português</title>
        <begindate>2020.10.29</begindate>
        <enddate>2020.11.03</enddate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <url>http://www.di.uminho.pt/~jcr</url>
        </supervisor>
    </meta>
    <workteam>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <url>https://github.com/luiscvnha</url>
        </member>
    </workteam>
    <abstract>
        <p>As stylesheets XSL ajudam na visualização da informação contida nos arquivos em XML.</p>
        <p>Foi criado um DTD para o arquivo de dados, o que ajudou na estruturação da stylesheet XSL.</p>
        <p>A stylesheet produzida cria um índice de arqueossítios, que redirecionam para a página
            do arqueossítio em questão, e a partir da qual é possível voltar para a página
            do índice na posição clicada.</p>
    </abstract>
    <deliverables>
        <deliverable url="arq.dtd">DTD</deliverable>
        <deliverable url="arqsite.xsl">XSL stylesheet</deliverable>
    </deliverables>
</pr>

=== luiscvnha/DAW2020/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <meta>
        <keyname></keyname>
        <title>T2: Definição de tipo de documento (DTD) para Project Records</title>
        <begindate>2020.10.25</begindate>
        <enddate>2020.10.27</enddate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <url>http://www.di.uminho.pt/~jcr</url>
        </supervisor>
    </meta>
    <workteam>
        <member id="a84244">
            <name>Luís Cunha</name>
            <email>a84244@alunos.uminho.pt</email>
            <url>https://github.com/luiscvnha</url>
        </member>
    </workteam>
    <abstract>
        <p>
            O objetivo deste trabalho é criar um
            <a href="https://en.wikipedia.org/wiki/Document_type_definition"><b>DTD</b></a>
            que defina a linguagem de anotação em
            <b><a href="https://en.wikipedia.org/wiki/XML">XML</a></b>
            do tipo <i>Project Record</i>.
        </p>
        <p>Deste modo, conseguimos validar os documentos do tipo Project Record, garantindo que respeitam todas as regras.</p>
    </abstract>
    <deliverables>
        <deliverable url="pr.dtd">Document Type Definition do Project Record</deliverable>
    </deliverables>
</pr>
